name = "static-cow"
main = "./functions/index.ts"
compatibility_date = "2026-05-23"

[[d1_databases]]
binding = "SUBSCRIBERS_DB"
database_name = "SUBSCRIBERS_DB"
database_id = "7002e4e4-c085-4b1b-95c4-0e340a4409aa"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = ["/api/*"]